exclude: ^pairinteraction/unit_test/integration_test_referencedata.txt$|^LICENSE(.*).txt$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
  # Formatters (hooks that re-write files) and linters (hooks that check but don't alter files)
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["-i", "--style=file"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: remove-tabs
        exclude: ^apple/Info.plist$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.274
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: ["--line-length", "120"]
  # Jupyter notebook specific tools
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-ruff
        args: ["--ignore=E402,I001", "--fix", "--exit-non-zero-on-fix"]
      - id: nbqa-black
